version: 2.1

jobs:
  create-and-push-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Extraire le message du commit"
          command: |
            commit_message=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            branch_name=$(echo $commit_message | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-')
            git config user.name "HermesRhoDev"
            git config user.email "materrazzi.pro@gmail.com"
            git checkout -b $branch_name
            git push origin $branch_name

workflows:
  create-and-push-branch-workflow:
    jobs:
      - create-and-push-branch