version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Afficher le message du commit"
          command: |
            git log --format=%B -n 1 $CIRCLE_SHA1

workflows:
  say-hello-workflow:
    jobs:
      - say-hello